package com.coloza.demo.springtest.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

/**
 * A Review document.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "Reviews")
public class Review {
    /**
     * The ID, or primary key, of the Review, as generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The product ID for which this review is applicable.
     */
    private Integer productId;

    /**
     * The version of the review, which is an increasing number starting with 1.
     */
    @Builder.Default
    private Integer version = 1;

    /**
     * A list of review entries - these contain user reviews of the product.
     */
    @Builder.Default
    @Setter(AccessLevel.NONE)
    private List<ReviewEntry> entries = new ArrayList<>();
}
